const moment = require('moment');

module.exports = {
    SELLERSETTINGGROUP: 'sellerSettingGroup',
    IDTYPE: 'SellerSKU',
    GET_FLAT_FILE_OPEN_LISTINGS_DATA_: '_GET_FLAT_FILE_OPEN_LISTINGS_DATA_',// 31433386895018805
    GET_MERCHANT_LISTINGS_ALL_DATA_: '_GET_MERCHANT_LISTINGS_ALL_DATA_',// 31443344300018805 imp
    GET_MERCHANT_LISTINGS_ALL_DATA_SP_API: 'GET_MERCHANT_LISTINGS_ALL_DATA',// 31443344300018805 imp
    GET_MERCHANT_LISTINGS_DATA_: '_GET_MERCHANT_LISTINGS_DATA_',// 31446012394018805 imp
    GET_MERCHANT_LISTINGS_INACTIVE_DATA_: '_GET_MERCHANT_LISTINGS_INACTIVE_DATA_',// 31432986054018805
    GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT_: '_GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT_',// 31436125881018805
    GET_FBA_MYI_ALL_INVENTORY_DATA: '_GET_FBA_MYI_ALL_INVENTORY_DATA_', //31504402812018807
    GET_FBA_MYI_ALL_INVENTORY_DATA_SP_API: 'GET_FBA_MYI_ALL_INVENTORY_DATA', //31504402812018807
    GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT: '_GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT_',
    MATCHING_PRODUCT_LIST_LIMIT: 5,
    OVERSIZE_WEIGHT: 70,//lbs
    OVERSIZE_LENGTH: 60,//inch
    OVERSIZE_WIDTH: 30,//inch
    INVENTORY_PLANNER: 'inventoryPlanner',
    INVENTORY_PLANNER_SERVICE_URL: 'https://app.inventory-planner.com/api/v1/purchase-orders',
    MARKETPLACE_ID_US: "ATVPDKIKX0DER",
    MARKETPLACE_ID_CA: "A2EUQ1WTGCTBG2",
    productDefault: () => ["","","","",false,"",false,false,false,"","","","",0,"","","","","","","","","","",moment().format("YYYY-MM-DD HH:mm:ss"),"","","",false,0,0,0,"","","","","",0,0,"",""]
}
