module.exports = {
    login: "select user from users where username= {}",
    updateSetting: 'update settings set settings= ? where username=? and settinggroup =?',
    addSetting: 'INSERT INTO settings SET ?',
    getSetting: 'select * from settings where username=? and settinggroup =?',
    getProduct: `SELECT * from products where user=?`,
    getSKU: `SELECT sellerSKU,CONCAT_WS('',sellerSKU,'-', itemName) as name FROM products where user=?`,
    addProduct: 'insert into products(sellerId,user,itemName,sellerSKU,status,itemNote,dateAdded,amazonASIN,productId,productIdType) VALUES ?',
    updateProduct: 'update products set itemName=?,status=?,itemNote=?,productId=?,productIdType=? where sellerId=? and sellerSKU=?',
    updateProductDetailsbyId: 'update products set 	amazonOversized=?, imageUrl=?,imageHeight=?,imageWidth=?,packageDimensions=?,dimensions=? where sellerSKU=?',
    updateFNSKU: 'update products set amazonFNSKU=? where sellerId=? and sellerSKU=?',
    addLastSynch: 'insert into lastSyne SET ?',
    selectLastSynch: 'SELECT timespan FROM `lastSyne` WHERE username=? and sellerId=? order by timespan DESC LIMIT 1',
    getSuppliers: 'select * from suppliersList where user=?',
    addSuppliers: 'INSERT INTO suppliersList SET ?',
    deleteSuppliers: 'delete from suppliersList where id=? and user=?',
    updateSuppliers: 'update suppliersList SET ? where id=? and user=?',
    updateProductUI: 'update products SET ? where user=? and sellerSKU=?',
    productSuppliers: 'select s.*,sl.supplierName from suppliers s  INNER join suppliersList sl on s.supplierID=sl.id where s.user=? and s.productSKU =?',
    addProductSuppliers: 'insert into suppliers SET ?',
    updateProductSuppliers: 'update suppliers SET ? where user=? and productSKU=? and supplierID=?',
    deleteProductSuppliers: 'delete from suppliers where user=? and productSKU=? and supplierID=?',
}